### ISSUE TITLE
Unfreezing variables causes bad memory accesses in SimpSolver 

### ISSUE THREAD

**Issue by fkutzner** [Udopia/candy-kingdom#34]
This only affects calls to setFrozen(int,bool) performed by clients of SimpSolver, not by SimpSolver itself.

Backtrace of test RSARARSolver.acceptanceTest_problem_flat200_1_FREEZEsimp:

```
==91643==ERROR: AddressSanitizer: container-overflow on address 0x62100002b160 at pc 0x00010055e48e bp 0x7fff5fbf8b90 sp 0x7fff5fbf8b88
READ of size 4 at 0x62100002b160 thread T0
    #0 0x10055e48d in Candy::SimpSolver<Candy::DefaultPickBranchLit>::ElimLt::cost(int) const SimpSolver.h:137
    #1 0x10055de74 in Candy::SimpSolver<Candy::DefaultPickBranchLit>::ElimLt::operator()(int, int) const SimpSolver.h:142
    #2 0x10055c8eb in Glucose::Heap<Candy::SimpSolver<Candy::DefaultPickBranchLit>::ElimLt>::percolateUp(int) Heap.h:55
    #3 0x1005568cf in Glucose::Heap<Candy::SimpSolver<Candy::DefaultPickBranchLit>::ElimLt>::insert(int) Heap.h:130
    #4 0x1005c3646 in Glucose::Heap<Candy::SimpSolver<Candy::DefaultPickBranchLit>::ElimLt>::update(int) Heap.h:117
    #5 0x1005c3470 in Candy::SimpSolver<Candy::DefaultPickBranchLit>::updateElimHeap(int) SimpSolver.h:179
    #6 0x10055ba72 in Candy::SimpSolver<Candy::DefaultPickBranchLit>::setFrozen(int, bool) SimpSolver.h:112
    #7 0x100da10b0 in Candy::GlucoseAdapter::setFrozen(int, bool) SolverAdapter.cc:85
    #8 0x100de5833 in Candy::ARSolverImpl::addInitialApproximationClauses(Candy::EncodedApproximationDelta&) ARSolver.cc:332
    #9 0x100e0af98 in Candy::ARSolverImpl::solve() ARSolver.cc:453
    #10 0x100e05887 in Candy::ARSolverImpl::solve(Candy::CNFProblem&) ARSolver.cc:431
    #11 0x100b77f40 in Candy::test_acceptanceTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Candy::SimplificationHandlingMode, bool, bool) ARSolverTests.cc:372
    #12 0x100b1abea in Candy::test_acceptanceTest_problem_flat200(int, Candy::SimplificationHandlingMode, bool, bool) ARSolverTests.cc:380
    #13 0x100b1b380 in Candy::RSARARSolver_acceptanceTest_problem_flat200_1_FREEZEsimp_Test::TestBody() ARSolverTests.cc:408

```

**Comment by Udopia** [comment]
not applicable any longer
